version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ommani@2022@Hack
      MYSQL_ROOT_HOST: localhost
      MYSQL_DATABASE: ocop
      MYSQL_USER: ocop
      MYSQL_PASSWORD: ommani@2022@Hack
    networks:
      - ommanilife
  phpmyadmin:
      depends_on:
          - db
      image: phpmyadmin/phpmyadmin
      restart: always
      volumes:
          - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      ports:
          - '8080:80'
      environment:
          PMA_HOST: db
          MYSQL_ROOT_PASSWORD: ommani@2022@Hack
      networks:
          - ommanilife
networks:
  ommanilife:
volumes:
  db_data:
