version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: ocop
        container_name: ocop
        restart: unless-stopped
        user: root
        tty: true
        working_dir: /var/www
        depends_on:
            -   db
        volumes:
            - ./:/var/www
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - ommanilife
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - ommanilife
    db:
        image: mysql:5.7
        container_name: db
        volumes:
            - db_data:/var/lib/mysql
            - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
        restart: always
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: iMIXiDiewOrqUEsT
            MYSQL_ROOT_HOST: localhost
            MYSQL_DATABASE: ocop
            MYSQL_USER: ocop
            MYSQL_PASSWORD: iMIXiDiewOrqUEsT
        networks:
            - ommanilife
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        volumes:
            - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        ports:
            - '8080:80'
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: iMIXiDiewOrqUEsT
        networks:
            - ommanilife
networks:
    ommanilife:
        external:
            name: ommanilife
volumes:
    db_data:
